---
- hosts: 127.0.0.1
  connection: localhost
  become: true
  vars:
    fly_version: 5.5.1

  tasks:
  - name: "update package manager"
    package:
      name: '*'
      state: latest
    ignore_errors: yes
    tags:
      - kernel
      - git
      - vault

  - name: "Installing Git"
    package: pkg={{ item }} state=installed
    with_items:
      - git
    ignore_errors: yes
    tags:
      - git

  - name: "Installing unzip"
    package: pkg={{ item }} state=installed
    with_items:
      - unzip
    ignore_errors: yes
    tags:
      - vault

  - name: "Install docker-compose"
    get_url:
      url: "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-{{ ansible_system }}-{{ ansible_userspace_architecture }}"
      dest: /usr/local/bin/docker-compose
      mode: '0755'
    tags:
      - docker-compose

  - name: "Installing fly"
    unarchive:
      src: "https://github.com/concourse/concourse/releases/download/v{{ fly_version }}/fly-{{ fly_version }}-linux-amd64.tgz"
      dest: /usr/local/bin/
      remote_src: yes
      keep_newer: no
      mode: '0755'
    tags:
      - fly

  - name: "Download lastest stable version of jq"
    get_url:
      url: "https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64"
      dest: /usr/local/bin/jq
      mode: '0755'
    tags:
      - jq

  - name: "Install vault cli"
    unarchive:
      src: "https://releases.hashicorp.com/vault/1.2.3/vault_1.2.3_linux_amd64.zip"
      dest: /usr/local/bin/
      remote_src: yes
      keep_newer: no
      mode: '0755'
    tags:
      - vault

  - name: "Disable Centos FireWall Service"
    systemd:
      name: firewalld
      state: stopped
      enabled: no
    when: ansible_facts['distribution'] == "CentOS"
    tags:
      - docker

  - name: "Disable Ubuntu FireWall Service"
    systemd:
      name: ufw
      state: stopped
      enabled: no
    when: ansible_facts['distribution'] == "Ubuntu"
    tags:
      - docker

  - name: Add Docker repo
    get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docer-ce.repo
    when: ansible_facts['distribution'] == "CentOS"
    tags:
      - docker

  - apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
      state: present
    when: ansible_facts['distribution'] == "Ubuntu"
    tags:
      - docker

  - name: "Install Docker-CE"
    package:
      name: docker-ce
      state: present
    tags:
      - docker

  - name: Creates directory
    file:
      path: /etc/systemd/system/docker.service.d
      state: directory
    tags:
      - docker

  - name: "Make sure the service starts at boot and is currently started"
    systemd:
      name: docker
      daemon_reload: yes
      state: started
      enabled: yes
    tags:
      - docker

  - name: Adding user to docker
    user: name='{{ lookup("env", "USER") }}'
          group=docker
    tags:
      - docker

  - name: "Add gpg key for repo"
    rpm_key:
      state: present
      key: https://www.elrepo.org/RPM-GPG-KEY-elrepo.org
    tags:
      - kernel

  - name: "Enable kernel repo"
    yum:
      name: "https://www.elrepo.org/elrepo-release-7.0-3.el7.elrepo.noarch.rpm"
      state: present
    tags:
      - kernel

  - name: "Upgrade Kernel"
    yum:
      name: kernel-ml
      enablerepo: elrepo-kernel
      state: present
    tags:
      - kernel

  - name: "Set Default Kernel to 5.x in grub"
    command: grub2-set-default 0
    tags:
      - kernel

  - name: Reboot a slow machine that might have lots of updates to apply
    reboot:
      reboot_timeout: 3600
    tags:
      - kernel
