---
- name: "Download lastest stable version of docker-compose"
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-{{ ansible_system }}-{{ ansible_userspace_architecture }}"
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x'
  tags:
    - docker-compose
